#server:
#  port: 8080
#  servlet:
#    context-path:/identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/saleappdb"
    username: 'root'
    password: 'chithien26@'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true